### ISSUE TITLE
你好，博客里面的图片没了，能重新换个图床么，谢谢

### ISSUE THREAD

**Issue by kangkang623** [xiaocao666tzh/Airport-Checkin#6]
另外支持的鸡场基于SS-Panel基于V2Board这两个没有区别么

**Comment by xiaocao666tzh** [comment]
图片本地貌似忘记备份了，到时候我去看看吧，最近比较忙。另外，我记得V2Board的jc默认没有签到吧，如果想支持的话可以自己修改代码

**Comment by xiaocao666tzh** [comment]
图床用的朋友的，他那里aws权限出了点问题，可能短时间内无法恢复。暂时也不打算更换图床，等朋友维护吧

**Comment by kangkang623** [comment]
好吧。。非常感谢。。。
